# Generated by Django 5.0.2 on 2024-03-14 14:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='created_on',
            field=models.DateField(verbose_name=datetime.datetime(2024, 3, 14, 22, 11, 16, 498541)),
        ),
    ]
