# Generated by Django 5.0.2 on 2024-03-14 15:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0004_alter_recipe_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='created_on',
            field=models.DateField(verbose_name=datetime.datetime(2024, 3, 14, 23, 21, 39, 394774)),
        ),
    ]
